Fix method_missing magic: only loop when we see an exception we think we caused ourselves.
For example:

application "example" do
  hahaha "whatever"
end

before: 
No resource found for whatever. Tried application_hahaha, application_python_hahaha...

after:

NoMethodError: undefined method `application_hahaha' for #<…>